apiVersion: v1
kind: Service
metadata:
  name: knote
spec:
  selector:
    app: knote
  ports:
    - port: 8080
      nodePort: 30036
  type: NodePort    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: appss
          image: phantomlk/testnode:v1
          ports:
            - containerPort: 8080         
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"